"""empty message

Revision ID: f54d9c32c5c9
Revises: c16cad08ef1d
Create Date: 2020-05-09 19:04:33.397649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54d9c32c5c9'
down_revision = 'c16cad08ef1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_tittle', sa.String(length=100), nullable=True),
    sa.Column('photo_description', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_tittle'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_photo_created'), 'photo', ['created'], unique=False)
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_tags')
    op.drop_index(op.f('ix_photo_created'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
